apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-client
  namespace: submission-service
  annotations:
    contact: "abhinav.jindal"
  labels:
    version: "1.0.0"
spec:
  containers:
  - name: ubuntu-client
    image: ubuntu:latest
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"