apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-client
  namespace: raas-submission-service
  annotations:
    avalara.io/contact: "dg-in-raas-submission-squad@avalara.com"
    avalara.io/department: "returns"
    avalara.io/team: "TEAM-00226"
    deployment.avalara.io/pipeline: "https://scm.platform.us-west-2.avalara.io/raas/raas-solutions/raas-platform-solution/-/pipelines/2727901"
    inventory.avalara.io/appid: "APP-01037"
    inventory.avalara.io/cmpid: "CMP-00972"
    reliability.avalara.io/escalation: "apoorva.dabri@avalara.com"
    security.avalara.io/data-class: "internal"
    security.avalara.io/user-data: "false"
  labels:
    avalara.io/version: "1.0.0" # The current version of the resource (semver, commit, hash, etc)
    avalara.io/component: "app" # The component within the architecture
    avalara.io/managed-by: "helm" # The tool being used to manage this resource
    avalara.io/environment: "dev" # The runtime environment of this resource
    avalara.io/part-of: "raas-data-service-mesh-core" # The gitlab repository of the team/service that owns this resource
spec:
  containers:
  - name: ubuntu-client
    image: ubuntu:latest
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"