# Reference: https://artifacthub.io/packages/helm/bitnami/redis

global:
  defaultStorageClass: default

commonAnnotations:
  contact: "abhinav.jindal"

commonLabels:
  version: "1.0.0"
  
master:
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
  persistence:
    enabled: true
    size: 2Gi

architecture: replication

replica:
  replicaCount: 3
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
  persistence:
    enabled: true
    size: 2Gi

sentinel:
  enabled: true
  quorum: 2
  replicaCount: 3
  usePassword: true

tls:
  enabled: false
auth:
  enabled: false

# Uncomment for production
# auth:
#   enabled: true
#   sentinelPassword: "sentinel"
#   password: "redis"

# tls:
#   enabled: true
#   existingSecret: cluster-wildcard-tls

metrics:
  enabled: false
